//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chart_public_transportation
{
    using System;
    using System.Collections.Generic;
    
    public partial class taxi_area
    {
        public string 연도 { get; set; }
        public double 도심권 { get; set; }
        public double 동북권 { get; set; }
        public double 서북권 { get; set; }
        public double 서남권 { get; set; }
        public double 동남권 { get; set; }
    }
}
